Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')

Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|

  	web.vm.box = "bento/centos-6.7"
  	web.vm.provision :shell, path: "bootstrap.sh"
	web.vm.define "omp_web1"
  	web.vm.network :forwarded_port, guest: 80, host: 8080
 	web.vm.network :forwarded_port, guest: 8081, host: 8081

  	web.vm.network "private_network", ip: "192.168.33.10"
  	web.vm.synced_folder ".", "/vagrant"
  end
end
